gen_templates_opts:
  _target_: utils.config.GenTemplatesOpts
  dataset_name:
  object_lids:
  version: v1
  num_viewspheres: 1
  min_num_viewpoints: 57
  num_inplane_rotations: 14
  images_per_view: 1
  max_num_triangles: 20000
  back_face_culling: false
  texture_size: [1024, 1024]
  ssaa_factor: 4.0
  background_type: gray
  light_type: multi_directional
  features_patch_size: 14
  crop: true
  crop_rel_pad: 0.05
  crop_size: [280, 280]
  features_patch_size:: 14
  save_templates: true
  overwrite: false
  debug: true

gen_repre_opts:
  _target_: utils.config.GenRepreOpts
  dataset_name:
  object_lids:
  version: v1
  templates_version: v1
  extractor_name: dinov2_vits14-reg
  grid_cell_size: 14.0
  apply_pca: true
  pca_components: 256
  cluster_features: true
  cluster_num: 2048
  debug: true
  overwrite: true
  pca_whiten: false
  pca_max_samples_for_fitting: 100000
  template_desc_opts:
    desc_type: tfidf
    tfidf_knn_k: 3
    tfidf_soft_assign: false
    tfidf_soft_sigma_squared: 10.0
